#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/ee-go"

REPLACEMENT="${1:-"../ee-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/stainless-sdks/ee-go="$REPLACEMENT"
go mod tidy -e
